#!/bin/bash
# poetry run pip install torch==1.11.0+cu116 -f https://download.pytorch.org/whl/cu113/torch_stable.html
# poetry run pip install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
poetry run pip install torch==1.13.0+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
