#!/bin/bash
# poetry run pip install torch==1.11.0+cu116 -f https://download.pytorch.org/whl/cu113/torch_stable.html
poetry run pip install torch --extra-index-url https://download.pytorch.org/whl/cu116
